language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install pytest
  - pip install coverage
  - pip install coveralls
# command to run tests
script: coverage run --source=receipteval setup.py test
after_success:
  - coveralls
  - coverage report -m
